### ISSUE TITLE
Tumblr - Design carousel

### ISSUE THREAD

**Issue by J-0987** [J-0987/PocketMonsterBattler#35]

**Comment by BryanPeens** [comment]
- Created carousel component using tailwind wind UI ( [Carousel](https://wind-ui.com/components/carousels/) with controls inside )

- Carousel animation using [glide.js](https://glidejs.com/)

- **Blockers** : getting more images from tumblr api, filter does not use limit yet and cant seem to sort results.

![Image](https://github.com/J-0987/PocketMonsterBattler/assets/33881213/9567a641-17c2-4fbc-ad75-a6acbeb90812)

**Comment by BryanPeens** [comment]
complete
